### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by obelisk-dev** [link-blockchain/ethereum-explorer#1]
![screenshot from 2017-07-09 14-34-23](https://user-images.githubusercontent.com/28880389/27996667-0e663774-64b5-11e7-91c3-3e261f9a1dd8.png)

Any ideas on this issue.  Tried removing and reinstalling webpack-dev-server as well 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@5.1.0
3 info using node@v7.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Ethereum_explorer@1.0.0~prestart: Ethereum_explorer@1.0.0
6 info lifecycle Ethereum_explorer@1.0.0~start: Ethereum_explorer@1.0.0
7 verbose lifecycle Ethereum_explorer@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle Ethereum_explorer@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/gideon/exp/ethereum-explorer/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle Ethereum_explorer@1.0.0~start: CWD: /home/gideon/exp/ethereum-explorer
10 silly lifecycle Ethereum_explorer@1.0.0~start: Args: [ '-c', 'webpack-dev-server' ]
11 silly lifecycle Ethereum_explorer@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle Ethereum_explorer@1.0.0~start: Failed to exec start script
13 verbose stack Error: Ethereum_explorer@1.0.0 start: `webpack-dev-server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:194:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid Ethereum_explorer@1.0.0
15 verbose cwd /home/gideon/exp/ethereum-explorer
16 verbose Linux 4.4.0-53-generic
17 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 verbose node v7.10.0
19 verbose npm  v5.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error Ethereum_explorer@1.0.0 start: `webpack-dev-server`
22 error Exit status 1
23 error Failed at the Ethereum_explorer@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by desertedisland** [comment]
Hi @ethericsol, Thanks for letting me know, this was a problem using ES6 module syntax in the webpack config file which has now been fixed. Cheers!
